modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/RobertSkalko/auto_repair_kit"
[[mods]]
modId = "auto_repair_kit"
version = "1.0.3"
displayName = "Auto Repair Kits"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://www.curseforge.com/minecraft/mc-mods/auto-repair-kits"
logoFile = "icon.png"
credits = ""
authors = "mcrobertx22"
description = '''
Auto repair your items with rechargable kits!
'''
[[dependencies.auto_repair_kit]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.auto_repair_kit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.auto_repair_kit]]
modId = "library_of_exile"
mandatory = true
versionRange = "[1.5.5,)"
ordering = "NONE"
side = "BOTH"